ISSUE_TEMPLATEを追加
postdcc/translation_request pull request #1
Opened 2017-04-26 09:00 UTC by mk2

翻訳リクエストを受け付ける際のイシューテンプレートを作成しました。レビューお願いします。

2017-04-26 09:41 UTC, re-fort commented on .github/ISSUE_TEMPLATE.md
> +    例: 著者の連絡先が不明な場合
`著者から翻訳許諾がもらえない場合`の方が一般的な気がするのでいいかなーと。

2017-04-26 09:43 UTC, re-fort requested changes
1点コメント記載しました。

2017-04-27 12:04 UTC, re-fort approved these changes

2017-04-27 12:05 UTC, re-fort commented
LGTM✨

2017-04-27 16:56 UTC, remore commented
僕も気になったのは採用されない部分の例の表記ですね。
今例示されている以外にも、編集部の方で投票した結果採用されないケースとかもあるから、その辺のジャッジルール含めて別ドキュメントで説明しておくか、そういうのがないのであればここの例をもう少し豊富に書かないと、Requestしてみたけど「不採用でした、Requestありがとうございました」みたいな結果をご連絡することが多くなってしまいそうな。

2017-05-08 09:57 UTC, mk2 commented
@remore 

確かに翻訳リクエストのリジェクト理由が網羅しといたほうが良さそうだと思ったので、トップディレクトリにreject_examples.mdファイルを作成しました。こちらもレビューお願いします。

2017-05-17 06:38 UTC, remore approved these changes
:heart:

2017-05-18 05:54 UTC, merged