READMEに記事リクエストの出し方を追加（Githubのnew issueを立てる方法のみ）
postdcc/translation_request pull request #2
Opened 2017-05-24 02:56 UTC by mk2

READMEに記事リクエストの出し方を追加しました。レビューお願いします。

2017-05-24 03:01 UTC, re-fort commented on README.md
> +### POSTDウェブサイト
s/POSTDウェブサイト/POSTDウェブサイトから出す場合/

2017-05-24 03:02 UTC, re-fort requested changes
チェックしました〜

2017-05-31 05:21 UTC, mk2 commented
@re-fort 
修正した

2017-06-06 02:48 UTC, re-fort approved these changes

2017-06-06 02:52 UTC, re-fort commented
approveしてしまったけど、スパム対策でgithubからの一本化する方向に変えてしまっていいと思う

2017-06-06 05:20 UTC, merged