・翻訳リクエストを出した後の流れをREADMEに追加
postdcc/translation_request pull request #5
Opened 2017-06-21 11:23 UTC by mk2

翻訳リクエストを出した後の扱い方についてREADMEに追記しました。

確認とレビューをお願いします。

2017-06-21 11:32 UTC, remore approved these changes
🙆

2017-06-22 10:07 UTC, re-fort requested changes
レビューしました〜

2017-06-22 10:07 UTC, re-fort commented on README.md
> +3. 「Accpeted」ラベルが貼られた翻訳リクエストのissueについては、記事を翻訳し公開するまでクローズしません。「Rejected」ラベルが貼られた翻訳リクエストのissueについては、その時点でissueをクローズします。
著者から翻訳許諾がもらえない場合はAcceptedがRejectedになる可能性があることには触れたほうがいいかも

2017-06-23 03:26 UTC, mk2 commented on README.md
> +3. 「Accpeted」ラベルが貼られた翻訳リクエストのissueについては、記事を翻訳し公開するまでクローズしません。「Rejected」ラベルが貼られた翻訳リクエストのissueについては、その時点でissueをクローズします。
追記した。

2017-06-23 05:55 UTC, re-fort approved these changes
🙆

2017-06-23 06:09 UTC, satomi-yako commented
👍

2017-06-26 03:44 UTC, merged